import Head from 'next/head';
import React from 'react';
import NavMenu from '../nav/nav-menu.component';
import Sidebar from '../sidebar/sidebar.component';
import { WithLogin } from './index';

const Layout: React.FC = ({ children }) => {
  return (
    <div className={'flex flex-wrap w-full min-h-screen'}>
      <Head>
        <title>Peercode: Collaborative Learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <div className={'w-10/12 flex flex-col'}>
        <NavMenu />
        <div className={'p-5 text-white'}>
          <WithLogin>
            {children}
          </WithLogin>
        </div>
      </div>
    </div>
  );
};

export default Layout;
